version: "3.8"

services:
  # https://stackoverflow.com/questions/37536687/what-is-the-relation-between-docker0-and-eth0
  # https://docs.docker.com/network/host/
  # https://rmoff.net/2019/11/29/using-tcpdump-with-docker/
  tcpdump:
    build:
      context: ./tcpdump
      dockerfile: Dockerfile
    container_name: tcpdump
    image: tcpdump
    networks: 
      - trap_network

  listener:
    build:
      context: ./listener
      dockerfile: Dockerfile
    container_name: trap-listener
    image: trap-listener
    networks: 
      - trap_network
    depends_on: 
      - tcpdump
  
  sender:
    build:
      context: ./sender
      dockerfile: Dockerfile
    container_name: trap-sender
    image: trap-sender
    networks: 
      - trap_network
    depends_on: 
      - tcpdump
      - listener

networks:
  trap_network:
    driver: bridge